version: "3.9"
services:
  harmonizer:
    container_name: harmonizer
    build: .
    image: harmonizer:prod
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/backend/uploads
      - ./data:/app/backend/data
      - ./backend/ourspace_data:/app/backend/ourspace_data
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    command: --cleanup --rolling-restart harmonizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped




