services:
  - type: web
    name: harmonizer-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --config backend/gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PYTHONUNBUFFERED
        value: "1"
